{
 "title": "Kibana",
 "description": "Example dashboard provided by @pjhampton",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "HOST:",
    "query": "label_values(kibana_hostname, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Kibana Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "kibana_status" }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    { "expr": "kibana_millis_uptime" }
   ]
  },
  {
   "title": "Concurrent Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "kibana_concurrent_connections" }
   ]
  },
  {
   "title": "Heap Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": " kibana_heap_used_in_bytes / kibana_heap_max_in_bytes * 100"
    }
   ]
  },
  {
   "title": "Samples ingested (rate-5m)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kibana_os_load1", "legendFormat": "OS Load 1m" },
    { "expr": "kibana_os_load5", "legendFormat": "OS Load 5m" },
    { "expr": "kibana_os_load15", "legendFormat": "OS Load 15m" }
   ]
  },
  {
   "title": "Elasticsearch Plugin Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "kibana_plugin_elasticsearch" }
   ]
  },
  {
   "title": "Kibana Prometheus Exporter Plugin Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kibana_plugin_kibana_prometheus_exporter"
    }
   ]
  },
  {
   "title": "Kibana Machine Learning Plugin Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "kibana_plugin_ml" }
   ]
  }
 ]
}